import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { format } from "date-fns";

export function exportToPDF(expenses, username) {
  const doc = new jsPDF();
  doc.setFontSize(16);
  doc.text("Expense Report", 14, 15);
  doc.setFontSize(10);
  doc.text(`Generated by: ${username}`, 14, 22);
  doc.text(`Date: ${format(new Date(), "dd MMM yyyy")}`, 14, 28);

  autoTable(doc, {
    startY: 34,
    head: [["Title", "Category", "Amount (PKR)", "Date", "Status"]],
    body: expenses.map((e) => [
      e.title,
      e.category,
      Number(e.amount).toLocaleString(),
      format(new Date(e.date), "dd MMM yyyy"),
      e.status,
    ]),
    styles: { fontSize: 9 },
    headStyles: { fillColor: [99, 102, 241] },
  });

  doc.save(`expenses_${format(new Date(), "yyyy-MM-dd")}.pdf`);
}

export function exportToExcel(expenses, username) {
  const data = expenses.map((e) => ({
    Title: e.title,
    Category: e.category,
    "Amount (PKR)": e.amount,
    Date: format(new Date(e.date), "dd MMM yyyy"),
    Status: e.status,
    Description: e.description || "",
  }));

  const ws = XLSX.utils.json_to_sheet(data);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Expenses");
  XLSX.writeFile(wb, `expenses_${format(new Date(), "yyyy-MM-dd")}.xlsx`);
}
